-- Align the audit action enum with the current Prisma schema.
ALTER TYPE "AcaoAuditoria" ADD VALUE IF NOT EXISTS 'BACKUP_INICIADO';
ALTER TYPE "AcaoAuditoria" ADD VALUE IF NOT EXISTS 'BACKUP_CONCLUIDO';
ALTER TYPE "AcaoAuditoria" ADD VALUE IF NOT EXISTS 'BACKUP_FALHA';
ALTER TYPE "AcaoAuditoria" ADD VALUE IF NOT EXISTS 'RESTORE_INICIADO';
ALTER TYPE "AcaoAuditoria" ADD VALUE IF NOT EXISTS 'RESTORE_CONCLUIDO';
ALTER TYPE "AcaoAuditoria" ADD VALUE IF NOT EXISTS 'RESTORE_FALHA';
ALTER TYPE "AcaoAuditoria" ADD VALUE IF NOT EXISTS 'LGPD_EXPORTACAO';
ALTER TYPE "AcaoAuditoria" ADD VALUE IF NOT EXISTS 'LGPD_ANONIMIZACAO';
ALTER TYPE "AcaoAuditoria" ADD VALUE IF NOT EXISTS 'LIMPEZA_AUTOMATICA';
ALTER TYPE "AcaoAuditoria" ADD VALUE IF NOT EXISTS 'RETENCAO_EXECUTADA';
