export const dashboardApiSuccess = {
  "/analytics/dashboard": {
    clientes: {
      totalClientes: 42,
      clientesAtivos: 35,
      clientesInativos: 7,
      clientesAniversariantesMes: 4,
    },
    agendamentos: {
      totalAgendamentos: 28,
      confirmados: 8,
      cancelados: 3,
      concluidos: 14,
      pendentes: 3,
    },
    financeiro: {
      receitas: 8400,
      despesas: 2150,
      saldo: 6250,
      ticketMedio: 600,
    },
    fidelidade: {
      clientesComPontos: 18,
      pontosDistribuidos: 3600,
      beneficiosLiberados: 7,
    },
    pacotes: {
      pacotesAtivos: 12,
      pacotesFinalizados: 6,
      pacotesVencidos: 2,
    },
    whatsapp: {
      mensagensCriadas: 45,
      mensagensEnviadas: 0,
      campanhasCriadas: 3,
    },
  },
  "/analytics/clientes": {
    totalClientes: 42,
    ativos: 35,
    inativos: 7,
    novosUltimos30Dias: 6,
    aniversariantesMes: 4,
    crescimentoPercentual: 12.5,
  },
  "/analytics/agendamentos": {
    total: 28,
    confirmados: 8,
    cancelados: 3,
    concluidos: 14,
    pendentes: 3,
    taxaCancelamento: 10.71,
    taxaConclusao: 50,
  },
  "/analytics/financeiro": {
    receitas: 8400,
    despesas: 2150,
    saldo: 6250,
    ticketMedio: 600,
    receitasMes: 5200,
    despesasMes: 1300,
    crescimentoFinanceiro: 18.2,
  },
  "/analytics/servicos": [
    {
      ranking: 1,
      servico: "Corte executivo",
      quantidade: 16,
      receita: 2400,
    },
    {
      ranking: 2,
      servico: "Coloração",
      quantidade: 9,
      receita: 3150,
    },
  ],
  "/analytics/profissionais": [
    {
      ranking: 1,
      nome: "Ana Profissional",
      atendimentos: 18,
      receita: 5100,
      comissao: 1020,
    },
    {
      ranking: 2,
      nome: "Bruno Profissional",
      atendimentos: 10,
      receita: 3300,
      comissao: 660,
    },
  ],
  "/analytics/unidades": [
    {
      ranking: 1,
      unidade: "Unidade Centro",
      receita: 5400,
      agendamentos: 17,
      clientes: 0,
    },
    {
      ranking: 2,
      unidade: "Unidade Norte",
      receita: 3000,
      agendamentos: 11,
      clientes: 0,
    },
  ],
  "/analytics/fidelidade": {
    clientesComPontos: 18,
    pontosDistribuidos: 3600,
    pontosResgatados: 900,
    beneficiosLiberados: 7,
    topClientes: [
      {
        ranking: 1,
        clienteId: "cliente-interno-1",
        nome: "Cliente Fidelidade",
        telefone: "85999999999",
        pontos: 850,
      },
    ],
  },
  "/analytics/pacotes": {
    pacotesVendidos: 20,
    pacotesAtivos: 12,
    pacotesFinalizados: 6,
    pacotesVencidos: 2,
    receitaGerada: 7200,
  },
  "/analytics/whatsapp": {
    mensagensCriadas: 45,
    mensagensSimuladas: 45,
    mensagensEnviadas: 0,
    campanhasCriadas: 3,
    templatesAtivos: 5,
  },
  "/analytics/notificacoes": {
    totalNotificacoes: 38,
    lidas: 24,
    naoLidas: 10,
    arquivadas: 4,
  },
  "/analytics/eventos": {
    totalEventos: 31,
    porTipo: {
      AGENDAMENTO_CRIADO: 18,
      CLIENTE_ATUALIZADO: 8,
      PACOTE_VENDIDO: 5,
    },
    porModulo: {
      AGENDAMENTOS: 18,
      CLIENTES: 8,
      PACOTES: 5,
    },
    ultimosEventos: [],
  },
} satisfies Readonly<Record<string, unknown>>;

export const dashboardApiEmpty = {
  "/analytics/dashboard": {
    clientes: {
      totalClientes: 0,
      clientesAtivos: 0,
      clientesInativos: 0,
      clientesAniversariantesMes: 0,
    },
    agendamentos: {
      totalAgendamentos: 0,
      confirmados: 0,
      cancelados: 0,
      concluidos: 0,
      pendentes: 0,
    },
    financeiro: {
      receitas: 0,
      despesas: 0,
      saldo: 0,
      ticketMedio: 0,
    },
    fidelidade: {
      clientesComPontos: 0,
      pontosDistribuidos: 0,
      beneficiosLiberados: 0,
    },
    pacotes: {
      pacotesAtivos: 0,
      pacotesFinalizados: 0,
      pacotesVencidos: 0,
    },
    whatsapp: {
      mensagensCriadas: 0,
      mensagensEnviadas: 0,
      campanhasCriadas: 0,
    },
  },
  "/analytics/clientes": {
    totalClientes: 0,
    ativos: 0,
    inativos: 0,
    novosUltimos30Dias: 0,
    aniversariantesMes: 0,
    crescimentoPercentual: 0,
  },
  "/analytics/agendamentos": {
    total: 0,
    confirmados: 0,
    cancelados: 0,
    concluidos: 0,
    pendentes: 0,
    taxaCancelamento: 0,
    taxaConclusao: 0,
  },
  "/analytics/financeiro": {
    receitas: 0,
    despesas: 0,
    saldo: 0,
    ticketMedio: 0,
    receitasMes: 0,
    despesasMes: 0,
    crescimentoFinanceiro: 0,
  },
  "/analytics/servicos": [],
  "/analytics/profissionais": [],
  "/analytics/unidades": [],
  "/analytics/fidelidade": {
    clientesComPontos: 0,
    pontosDistribuidos: 0,
    pontosResgatados: 0,
    beneficiosLiberados: 0,
    topClientes: [],
  },
  "/analytics/pacotes": {
    pacotesVendidos: 0,
    pacotesAtivos: 0,
    pacotesFinalizados: 0,
    pacotesVencidos: 0,
    receitaGerada: 0,
  },
  "/analytics/whatsapp": {
    mensagensCriadas: 0,
    mensagensSimuladas: 0,
    mensagensEnviadas: 0,
    campanhasCriadas: 0,
    templatesAtivos: 0,
  },
  "/analytics/notificacoes": {
    totalNotificacoes: 0,
    lidas: 0,
    naoLidas: 0,
    arquivadas: 0,
  },
  "/analytics/eventos": {
    totalEventos: 0,
    porTipo: {},
    porModulo: {},
    ultimosEventos: [],
  },
} satisfies Readonly<Record<string, unknown>>;
